In [2]:
import re
import math
import numpy as np
from PIL import Image

# unos fotografije koja se obradjuje

h = int(input("Unesite 1 ukoliko unosite RGB fajl, a 2 ukoliko unosite crno-beli fajl:"))
if h == 1:
    file = input("Ime fajla:")
    my_string = np.asarray(Image.open(file),np.uint8)
    shape = my_string.shape
    a = my_string
    print ("Uneseni string je:",my_string)
    my_string = str(my_string.tolist())
elif h == 2:
    array = np.arange(0, 737280, 1, np.uint8)
    my_string = np.reshape(array, (1024, 720))
    print ("Uneseni string je:",my_string)
    a = my_string
    my_string = str(my_string.tolist())

else:
    print("Uneli ste ime nepostojeceg fajla")



# ucestanost pojavljivanja znakova
letters = []
only_letters = []
for letter in my_string:
    if letter not in letters:
        frequency = my_string.count(letter)
        letters.append(frequency)
        letters.append(letter)
        only_letters.append(letter)

nodes = []
while len(letters) > 0:
    nodes.append(letters[0:2])
    letters = letters[2:]                               # sorting according to frequency
nodes.sort()
huffman_tree = []
huffman_tree.append(nodes)                             #Make each unique character as a leaf node

def combine_nodes(nodes):
    pos = 0
    newnode = []
    if len(nodes) > 1:
        nodes.sort()
        nodes[pos].append("1")                       # assigning values 1 and 0
        nodes[pos+1].append("0")
        combined_node1 = (nodes[pos] [0] + nodes[pos+1] [0])
        combined_node2 = (nodes[pos] [1] + nodes[pos+1] [1])  # combining the nodes to generate pathways
        newnode.append(combined_node1)
        newnode.append(combined_node2)
        newnodes=[]
        newnodes.append(newnode)
        newnodes = newnodes + nodes[2:]
        nodes = newnodes
        huffman_tree.append(nodes)
        combine_nodes(nodes)
    return huffman_tree                                     # huffman tree generation

newnodes = combine_nodes(nodes)

huffman_tree.sort(reverse = True)
print("Huffman tree with merged pathways:")

checklist = []
for level in huffman_tree:
    for node in level:
        if node not in checklist:
            checklist.append(node)
        else:
            level.remove(node)
count = 0
for level in huffman_tree:
    print("Level", count,":",level)             #print huffman tree
    count+=1
print()

letter_binary = []
if len(only_letters) == 1:
    lettercode = [only_letters[0], "0"]
    letter_binary.append(letter_code*len(my_string))
else:
    for letter in only_letters:
        code =""
        for node in checklist:
            if len (node)>2 and letter in node[1]:           #genrating binary code
                code = code + node[2]
        lettercode =[letter,code]
        letter_binary.append(lettercode)
print(letter_binary)
print("Binary code generated:")
for letter in letter_binary:
    print(letter[0], letter[1])

bitstring =""
for character in my_string:
    for item in letter_binary:
        if character in item:
            bitstring = bitstring + item[1]
binary ="0b"+bitstring
print("Your message as binary is:")
                                        # binary code generated

uncompressed_file_size = len(my_string)*7
compressed_file_size = len(binary)-2
print("Your original file size was", uncompressed_file_size,"bits. The compressed size is:",compressed_file_size)
print("This is a saving of ",uncompressed_file_size-compressed_file_size,"bits")
output = open("compressed.txt","w+")
print("Compressed file generated as compressed.txt")
output = open("compressed.txt","w+")
print("Decoding.......")
output.write(bitstring)

bitstring = str(binary[2:])
uncompressed_string =""
code =""
for digit in bitstring:
    code = code+digit
    pos=0                                        #iterating and decoding
    for letter in letter_binary:
        if code ==letter[1]:
            uncompressed_string=uncompressed_string+letter_binary[pos] [0]
            code=""
        pos+=1

print("Your UNCOMPRESSED data is:")
if h == 1:
    temp = re.findall(r'\d+', uncompressed_string)
    res = list(map(int, temp))
    res = np.array(res)
    res = res.astype(np.uint8)
    res = np.reshape(res, shape)
    print(res)
    print("Observe the shapes and input and output arrays are matching or not")
    print("Input image dimensions:",shape)
    print("Output image dimensions:",res.shape)
    data = Image.fromarray(res)
    data.save('uncompressed.png')
    if a.all() == res.all():
        print("Success")
if h == 2:
    temp = re.findall(r'\d+', uncompressed_string)
    res = list(map(int, temp))
    print(res)
    res = np.array(res)
    res = res.astype(np.uint8)
    res = np.reshape(res, (1024, 720))
    print(res)
    data = Image.fromarray(res)
    data.save('uncompressed.png')
    print("Success")

def calculate_entropy(letter_binary):
    entropy = 0
    for letter_code in letter_binary:
        probability = my_string.count(letter_code[0]) / len(my_string)
        entropy -= probability * np.log2(probability)
    return entropy

entropy = calculate_entropy(letter_binary)
print("Entropy of the encoding:", entropy)

efikasnost = (uncompressed_file_size - compressed_file_size)/ uncompressed_file_size *100
print(efikasnost)

Unesite 1 ukoliko unosite RGB fajl, a 2 ukoliko unosite crno-beli fajl:1
Ime fajla:cat.jpg
Uneseni string je: [[[249 243 229]
  [247 241 227]
  [242 239 224]
  ...
  [111 107  95]
  [110 106  94]
  [111 107  95]]

 [[250 244 230]
  [249 243 229]
  [244 241 226]
  ...
  [110 107  92]
  [107 103  91]
  [106 103  88]]

 [[253 247 233]
  [251 245 231]
  [247 243 231]
  ...
  [110 104  88]
  [105  99  85]
  [102  96  80]]

 ...

 [[214 166 100]
  [212 164  98]
  [209 161  95]
  ...
  [ 97  71  54]
  [ 97  71  54]
  [ 97  71  54]]

 [[208 160  96]
  [206 158  94]
  [203 155  91]
  ...
  [ 98  72  55]
  [ 98  72  55]
  [ 98  72  55]]

 [[204 156  92]
  [201 153  89]
  [199 151  87]
  ...
  [100  74  57]
  [ 99  73  56]
  [ 99  73  56]]]
Huffman tree with merged pathways:
Level 0 : [[5929590, ',341[]0968752 ']]
Level 1 : [[2292975, ',341', '1'], [3636615, '[]0968752 ', '0']]
Level 2 : [[1585557, '[]0968', '1'], [2051058, '752 ', '0']]
Level 3 : [[1124999, ',', '1'], [1167976, '341', '0'], [205